-- V4__fix_action_type_enum.sql

ALTER TABLE t_idempotency_record
ALTER COLUMN action_type TYPE VARCHAR(50)
USING CASE action_type
    WHEN 0 THEN 'CREATE_APPLICATION'
    WHEN 1 THEN 'UPDATE_APPLICATION'
    WHEN 2 THEN 'CHANGE_APPLICATION_STATUS'
    WHEN 3 THEN 'CHANGE_APPLICATION_NOTES'
    WHEN 4 THEN 'DELETE_APPLICATION'
    WHEN 5 THEN 'ENRICH_APPLICATION'
END;